### ISSUE TITLE
Dataset page

### ISSUE THREAD

**Issue by geralddejong** [delving/culture-hub#104]
Styling of http://localhost:9000/bob/dataset needs attention.

**Comment by geralddejong** [comment]
I find the interaction with this page rather strange still.  I would expect create new dataset to be here rather than in a drop-down menu at the top right.  I'm starting to dislike that drop-down more and more because i keep having to go back to it and carefully mouse-over it.  Maybe that's just me.

**Comment by geralddejong** [comment]
This issue could have been closed, but now I think there's something to add:

I have datasets in my mongodb, and the sip-creator fetches this list, so it still exists.

However this shows none:

http://frieseverhalen.localhost:9000/bob/dataset

**Comment by geralddejong** [comment]
Correction.  That was apparently a result of something else, but the page is still a little ugly.

**Comment by zemyatin** [comment]
page should be lookin good now
