### ISSUE TITLE
Upload not updating hash?

### ISSUE THREAD

**Issue by geralddejong** [delving/culture-hub#128]
It appears that uploading a new version of a dataset is not updating the hash of its source.  I upload, successfully, and then when I upload again, it repeats uploading the source when it shouldn't.

I'm not sure, but in SipCreatorEndpoint.scala it looks like this happens:

```
175: DataSet.addHash(dataSet, fileName.split("__")(1).replaceAll("\\.", DOT_PLACEHOLDER), hash)
```

But that the dataset is not saved afterwards.   The save actually happens earlier within the receiveXxx() methods.

**Comment by geralddejong** [comment]
I think it doesn't appear for files other than source, because there is always another file (source is last) which accidentally causes the updated dataset document to be saved.

**Comment by geralddejong** [comment]
The differences i'm seeing are these:

```
<?xml version='1.0' encoding='UTF-8'?>
<delving-sip-source>
<input>
<_id>750000104</_id>
<PICA_PPN>750000104</PICA_PPN>
<PICA_0200>0001:06-07-78</PICA_0200>
```

and this is the file that's later downloaded, which will of course have a different hash:

```
<delving-sip-source >
<input id="750000104">


<PICA_PPN>750000104</PICA_PPN>
<PICA_0200>0001:06-07-78</PICA_0200>
```

Every record has these blank lines in the records.xml which is received upon downloading, but there is also a difference due to our having changed from id="" to <_id>.

Perhaps only the blank line will need attention.  I will research this further and see if i can point out a specific problem.

**Comment by geralddejong** [comment]
The records.xml being downloaded still produces the id="..." style records.

```
304:          pw.println("""<input id="%s">""".format(record.localRecordKey))
```

It should also create a file called source.xml rather than records.xml, since the file saved will be source.xml.gz.

**Comment by geralddejong** [comment]
There's also still spurious blank lines:

```
<input id="7">



<priref>7</priref>
<edit.source>collect>intern</edit.source>
.....
<institution.name>Fries Museum</institution.name>
<administration_name value="Schilderkunst tot 1925" option="Schilderkunst tot 1925"><text language="0">Schilderkunst tot 1925</text>
<text language="1">Schilderkunst tot 1925</text>
<text language="2">Schilderkunst tot 1925</text>
<text language="3">Schilderkunst tot 1925</text>
</administration_name>



</input>
```

This will change the hash.

**Comment by geralddejong** [comment]
Downloaded:

```
<delving-sip-source >
<input>
<_id>1</_id>
<priref>1</priref>
<edit.source>collect>intern</edit.source>
<edit.source>photo</edit.source>
<edit.source>collect>intern</edit.source>
<input.source>FileMakerPro</input.source>
<edit.time>14:54:55</edit.time>
<edit.time>12:37:39</edit.time>
<edit.time>16:05:56</edit.time>
<creator.history></creator.history>
<edit.name>t.kamerling</edit.name>
<edit.name>alina</edit.name>
<edit.name>Daniel</edit.name>
<input.name>Conversie AIS</input.name>
<creator.date_of_death></creator.date_of_death>
<creator.date_of_birth></creator.date_of_birth>
<edit.date>2011-03-15</edit.date>
<edit.date>2009-02-19</edit.date>
```

Previously uploaded:

```
<?xml version='1.0' encoding='UTF-8'?>
<delving-sip-source xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<input>
<_id>1</_id>
<priref>1</priref>
<edit.source>collect>intern</edit.source>
<edit.source>photo</edit.source>
<edit.source>collect>intern</edit.source>
<input.source>FileMakerPro</input.source>
<edit.time>14:54:55</edit.time>
<edit.time>12:37:39</edit.time>
<edit.time>16:05:56</edit.time>
<creator.history/>
<edit.name>t.kamerling</edit.name>
<edit.name>alina</edit.name>
<edit.name>Daniel</edit.name>
<input.name>Conversie AIS</input.name>
<creator.date_of_death/>
<creator.date_of_birth/>
<edit.date>2011-03-15</edit.date>
```

There are at least two differences.  The namespaces are missing, and the <..../> is replaced by <...></...>.

**Comment by geralddejong** [comment]
It seems as if the only differences now are in how tags are ended, and only involving redundant spaces before the end of the tag that the hub seems to add.

```
2c2
< <delving-sip-source xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
---
> <delving-sip-source xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" >
13c13
< <creator.history/>
---
> <creator.history />
18,19c18,19
< <creator.date_of_death/>
< <creator.date_of_birth/>
---
> <creator.date_of_death />
> <creator.date_of_birth />
43,45c43,45
< <reproduction.creator/>
< <reproduction.type/>
< <reproduction.date/>
---
> <reproduction.creator />
> <reproduction.type />
> <reproduction.date />
```

**Comment by geralddejong** [comment]
Fixed the above in branch hashes-fix, but now something else appears:

``````
<acquisition.notes>Aankoop van fa. Bluett &amp; Sons, London, juli 1958</acquisition.notes>```
``````

now becomes:

```
<acquisition.notes>Aankoop van fa. Bluett  Sons, London, juli 1958</acquisition.notes>
```

**Comment by geralddejong** [comment]
Fixed the entities problem in text, but now this:

It appears that the record ordering is different!

```
<production.date.start>1850</production.date.start>
<dimension.type>diameter</dimension.type>
<dimension.type>hoogte</dimension.type>
<production.date.end>1940</production.date.end>
<institution.place>Leeuwarden</institution.place>
<institution.name>Princessehof Leeuwarden</institution.name>
<reproduction.identifier_URL>..\..\..\Images PH\NO 05877.B [01].JPG</reproduction.identifier_URL>
<administration_name>Europa</administration_name>
<percentf>1700-1800</percentf>
<percentH>blauw en wit</percentH>
<percentG>Delft</percentG>
<percentD>3</percentD>
<percentC>21.2</percentC>
</input>
<input>
<_id>33680</_id>
<priref>33680</priref>
<edit.source>collect>intern</edit.source>
```

Afterwards, the next record is different:

```
<production.date.start>1850</production.date.start>
<dimension.type>diameter</dimension.type>
<dimension.type>hoogte</dimension.type>
<production.date.end>1940</production.date.end>
<institution.place>Leeuwarden</institution.place>
<institution.name>Princessehof Leeuwarden</institution.name>
<reproduction.identifier_URL>..\..\..\Images PH\NO 05877.B [01].JPG</reproduction.identifier_URL>
<administration_name>Europa</administration_name>
<percentf>1700-1800</percentf>
<percentH>blauw en wit</percentH>
<percentG>Delft</percentG>
<percentD>3</percentD>
<percentC>21.2</percentC>
</input>
<input>
<_id>33681</_id>
<priref>33681</priref>
<edit.source>collect>intern</edit.source>
```

**Comment by geralddejong** [comment]
Unfortunately, record order in MongoDB is not guaranteed, unless we're willing to cap the number of records:

http://www.mongodb.org/display/DOCS/Sorting+and+Natural+Order

A new strategy:

Uploading a file results in a file being uploaded, and retaining its hashed name and original contents.  It could be collected in a subdirectory somewhere named after the Spec, similar to the the way SIPCreatorWorkspace does it.  Only HASH_source.xml.gz would have to be saved there, and a history of these files could be maintained on the server, since only truly new versions of the file will be stored.

Downloading a source file would then amount to preparing it first by building the HASH_source.xml.gz on the hub (currently, since we're not updating records, the latest HASH_source.xml.gz could be given, since all records have come from there anyway).  Whenever someone tries to upload a HASH_source.xml.gz which has already been seen, the hub can refuse, whether it was one uploaded or one prepared for download.

**Comment by geralddejong** [comment]
Sorting records according to _id solved the record ordering problem.  Apparently just one corner case left, where a tag has no content, only attributes.

```
> <content.subject.tax.rank option="Nf" value="Nf"></content.subject.tax.rank>
1943166c1943166
< <content.subject.tax.rank option="Nf" value="Nf"/>
```

**Comment by manuelbernhardt** [comment]
This one can be closed after making a comprehensive spec for it. Started it but had no time to finish it.

**Comment by manuelbernhardt** [comment]
Note to self: add this to the new upload spec
