### ISSUE TITLE
Collaboration for user things

### ISSUE THREAD

**Issue by stillinsky** [delving/culture-hub#138]
Collaborators for objects
      - view: view, whether private or public scope
      - edit: edit meta-data
      - admin: add more collaborators

 Collaborators for collections
      - view: view, whether private or public scope
      - edit: add or remove objects to/from collection
      - admin: add more collaborators

 Collaborators for stories
      - view: view, whether private or public scope
      - edit: change the story
      - admin: add more collaborators

**Depends on**: #272

**Comment by stillinsky** [comment]
moved this to milestone 1.0 as we discuss feasiblility of this on Friday again.

**Comment by manuelbernhardt** [comment]
The deadline for this one is not realistic given the other things. We should reschedule.

Also the access rights for simple user collaborations are too complicated here. We don't need 3 levels of access rights - either someone collaborates or they don't - I also wouldn't like someone to be able to add more collaborators to my things. So I'd just have one collaborator level which makes it possible to:
- see items even if they are "private"
- modify the item
