### ISSUE TITLE
Admin space for organizations

### ISSUE THREAD

**Issue by stillinsky** [delving/culture-hub#142]
- manage owners of organization
- create and update teams
- DataSet control

**Comment by manuelbernhardt** [comment]
Reassigned to @ zemyatin: this is implemented but not linked. We need a sort of menu for this, which includes:

/organization/delving/admin
/organization/delving/dataset
/organization/delving/groups

**Comment by manuelbernhardt** [comment]
manage owners of org is a separate ticket
