### ISSUE TITLE
Search result - full view

### ISSUE THREAD

**Issue by stillinsky** [delving/culture-hub#143]

**Comment by manuelbernhardt** [comment]
Ok, at this point the view is there in `app/views/search/object.html`. @zemyatin the floor is yours

You will need to re-index the sample dataset (Verzetsmuseum) by:
- make sure that in application.conf, solr is set to the localhost value
- on a command-line, open up the culturehub dir and go to "extras/servlet-server" and then run `java -jar start.jar`
- in mongo, run `db.runCommand({renameCollection: "culturehub.Records.Verzetsmuseum", to: "culturehub.Records.delving_Verzetsmuseum"})`  (so no need to drop the db)
- then go to `http://localhost:9000/organizations/delving/dataset`and press re-index
- then go to `http://localhost:9000/delving/object/Verzetsmuseum/00001`
