### ISSUE TITLE
Link DataSet records to UserCollection

### ISSUE THREAD

**Issue by stillinsky** [delving/culture-hub#158]

**Comment by manuelbernhardt** [comment]
@geralddejong @kiivihal, design question: where to store the links?

At the moment I see these as array of the chID identifier to be stored in the UserCollection bucket - those should not change even if there is re-ingestion.

**Comment by geralddejong** [comment]
That would represent a limitation on the number of them, but the limit would be an outrageously high number, so I think it's a good approach.  12 bytes per ID, so about 350,000 IDs in a mongo document (assuming 4mb).

**Comment by manuelbernhardt** [comment]
OK. btw the size is now 16mb/doc. If someone does link so many things by hand he'll get flowers.

**Comment by manuelbernhardt** [comment]
See #223 for more thoughts on this, especially on the indexing side of things.
