### ISSUE TITLE
User account overview

### ISSUE THREAD

**Issue by stillinsky** [delving/culture-hub#159]
-admin page for user account
-link to this page from 'user menu'

**Comment by manuelbernhardt** [comment]
I can't really remember what should be on this page. I mean I guess there should be some settings in there, at some point. For the moment tough I'd say this won't make it into 1.0, we'll only have a profile edition page there until it is more clearly defined what this looks like.

**Comment by stillinsky** [comment]
we can leave it for later. It is about being able to control notification, emails, etc. Alos probably more interesting when we roll out organizational pages.
