### ISSUE TITLE
Include authenticityToken everywhere

### ISSUE THREAD

**Issue by manuelbernhardt** [delving/culture-hub#170]
Walk over all forms everywhere, make sure we have authenticityTokens set.

**Comment by manuelbernhardt** [comment]
Should be done everywhere.

**Comment by geralddejong** [comment]
I click on index, and i get:

http://frieseverhalen.localhost:9000/organizations/delving/dataset/Princessehof/index

Which says: Bad authenticity token

**Comment by kiivihal** [comment]
I have the same issue.
