### ISSUE TITLE
Lighttpd Round robin and OAUTH2 are not playing nicely

### ISSUE THREAD

**Issue by kiivihal** [delving/culture-hub#194]
It seems that when the Culture-Hub runs on port 80 between lighttpd we can upload datasets back to the server. Downloading goes fine. When you change the port from 80 to 9000 it works flawlessly.

**Comment by manuelbernhardt** [comment]
Is there a log entry or something that indicates more what is going on? I have a hard time seeing what is going wrong.

**Comment by geralddejong** [comment]
Only Sjoerd has seen this so far.  I'll see if I can reproduce it.

In case it's related, although probably not, I've made it so that the CultureHubClient avoids mentioning port number when it's :80.

**Comment by geralddejong** [comment]
The unknown response was this:

HTTP/1.1 411 Length Required [Content-Type: text/html, Content-Length: 357, Connection: close, Date: Mon, 14 Nov 2011 21:14:16 GMT, Server: lighttpd/1.4.28]

Indeed.. didn't see that one coming.

**Comment by geralddejong** [comment]
Could Content-Length get stripped somehow by lighttpd?

http://www.checkupdown.com/status/E411.html

**Comment by manuelbernhardt** [comment]
I found this:

http://webcache.googleusercontent.com/search?q=cache:HXncLMJtDmEJ:stackoverflow.com/questions/4087976/ajax-stopped-working-in-chrome-after-switching-to-lighttpd+lighttpd+jquery+content-type&cd=10&hl=de&ct=clnk&gl=at

(have a crappy connection so I used the google cache here).

This seems to suggest that the content-type set by the server is wrong. I will look into this; I'm afraid the error is going to be in that OAuth lib or so.

**Comment by manuelbernhardt** [comment]
Created a branch called `fix-194`. My connection is too bad to download the libs necessary to create a spec, so I will look into that later.

**Comment by manuelbernhardt** [comment]
Re-opened, I said attempt to fix, not fix

**Comment by manuelbernhardt** [comment]
Ok, this does not happen on the server-side. Sip-Creator should set the Content-Length header, even if the body is null

**Comment by geralddejong** [comment]
I'm sending a request for upload of a file and i watch it in the debugger setting the Content-Length to a nonzero value before it is sent.  I'm looking into this further, but it's not clear what else can be done.

**Comment by geralddejong** [comment]
Nailed it.  The uploading FileEntity was set to "chunked", which threw things off.
