### ISSUE TITLE
Remove label block from object creation page

### ISSUE THREAD

**Issue by manuelbernhardt** [delving/culture-hub#211]
http://frieseverhalen.localhost:9000/bob/object/add

**Comment by kiivihal** [comment]
I hope by remove you mean comment out in the source code and the routing
configuration.

On 18 November 2011 00:12, Manuel Bernhardt <
reply@reply.github.com

**Comment by manuelbernhardt** [comment]
yes

On Fri, Nov 18, 2011 at 10:17 AM, Sjoerd Siebinga
reply@reply.github.com
wrote:
