### ISSUE TITLE
create an object in edit collection view

### ISSUE THREAD

**Issue by stillinsky** [delving/culture-hub#227]
You should be able to upload objects in the edit collection view. For now you can only choose from objects which are already there

**Comment by manuelbernhardt** [comment]
I don't see how this would work exactly, because for now an object is something that can be one or more uploaded files and meta-data. But not only a simple file as such. Or do you mean an interface for creating and uploading objects on-the-fly? I think that would be a bit of an overkill, or?

**Comment by stillinsky** [comment]
Yes, I can see that it was just weird to me that you can only choose from onbjects you uploaded before. It is fine to move that to a later stage.

**Comment by manuelbernhardt** [comment]
I think we have a naming problem here:
- for me an object is not a file. It's a digital object that you create. So you don't upload it
- you can upload a file. But this you can only do when creating an object. So you cannot do that on the fly, it should be something more carefully done (IMO) than just adding something to a collection.

Hence I would not even allow that workflow.

**Comment by geralddejong** [comment]
I agree that uploading should be unavailable in the edit collection view, except of course for a link to the page for that.

**Comment by stillinsky** [comment]
Yes, sorry for the confusion. I just mean a way to get to the upload file or create object page. I think that would be sufficient. Maybe in the 'select object' popup a link to 'create object'

**Comment by manuelbernhardt** [comment]
Closing this, we will see what kind of feedback we get from people.
