### ISSUE TITLE
display more than one file per object 

### ISSUE THREAD

**Issue by stillinsky** [delving/culture-hub#233]
you can iupload several object into one object. It only shows the first one, but this should be enabled

**Comment by manuelbernhardt** [comment]
Assigning to @zemyatin, will also add some convenience methods

**Comment by stillinsky** [comment]
multiple thumbnails per objects should be displayable, e.g. for coins. So probably there should be an option to have several files per object which are displayable.

**Comment by stillinsky** [comment]
if two files are uploaded per objects there is no way of viewing this files, this should be fixed
