### ISSUE TITLE
'Browse collection' remove description

### ISSUE THREAD

**Issue by stillinsky** [delving/culture-hub#240]
Browse collection the description should be removed and the user should be added as descriptions might be lenghty.

**Comment by stillinsky** [comment]
As we want to user to write long descriptions we might end up with an ugly thumbnail page for objects, collections, stories if we display descritpions there. To display the owner of the story/collection/object seems to make mroe sense.

**Comment by zemyatin** [comment]
nassauTheme merge will contain this change
