### ISSUE TITLE
remove description in 'browse objects'

### ISSUE THREAD

**Issue by stillinsky** [delving/culture-hub#242]
replace by the user as description might be lengthy

**Comment by manuelbernhardt** [comment]
description is cut off at 100 chars.

**Comment by stillinsky** [comment]
Ok, makes sense and this also works. I think the owner of the object would be a more appropriate info to display, especially as the user cann then distinguish between user objects and institutional objects. This could also be moved to the next iteration as it works as it is now.

**Comment by zemyatin** [comment]
nassauTheme merge will contain this change
