### ISSUE TITLE
refine search is not working

### ISSUE THREAD

**Issue by stillinsky** [delving/culture-hub#243]
refine search by 'object' or 'collection'. does that mean it looks in object or collection description? Why is it a refinement?
looking for 'Happy' produces results where it is not clear where they are from. clicking on them produces 404

**Comment by manuelbernhardt** [comment]
What do you mean with "refine search"? Giving a URL would help

**Comment by stillinsky** [comment]
Ok, I searched for 'happy' which gives me this URL: http://frieseverhalen.delving.org:9001/search?query=happy
The refinement option are: Objects or Collections. I assume it works like a facet but could not test that. Results listed there are producing 404s.

**Comment by manuelbernhardt** [comment]
Takin this over, will look at the facets branch

**Comment by manuelbernhardt** [comment]
Is this still broken?

**Comment by stillinsky** [comment]
i think this issue changed a bit as search now improved, although facets are not there yet. 'Refine your search by' is empty

**Comment by manuelbernhardt** [comment]
Ah yes indeed, it is not yet configured on the server. We need to do
this, maybe I'll have a chance to look at it with Sjoerd and Gerald

On Mon, Dec 12, 2011 at 6:03 PM, Juliane Stiller
reply@reply.github.com
wrote:

**Comment by manuelbernhardt** [comment]
Refine search does work, but is not configured. I now added a number of default facets, more need to be configured.
