### ISSUE TITLE
link to organization landing page missing

### ISSUE THREAD

**Issue by stillinsky** [delving/culture-hub#244]
link to orhganization landing page is missing, should be integrated so user can get to institution

**Comment by manuelbernhardt** [comment]
There is a link in the user menu. From where do you want another link? For the moment we on purpose do not list organizations.

**Comment by stillinsky** [comment]
ok so there is no way to get to the organization landing page from anywhere at the portal if I am not the member of the organization?

**Comment by manuelbernhardt** [comment]
Not if you don't know the link :) So this is a missing feature. Also I am not quite sure where we would put this link and what organizations we should list. Especially that now we have a bug which makes that organizations are not yet node-dependent. I think it is OK not to list them for now.

So could we move this to a further time? It needs to be done in parallel with other work

**Comment by manuelbernhardt** [comment]
I close this until we have a project that explicitely needs organizational landing pages for "normal" users.
