### ISSUE TITLE
user name vs. full name

### ISSUE THREAD

**Issue by stillinsky** [delving/culture-hub#245]
the user name is under each thing the user owns but profile pages have a full name. the user name should identfy the user across the portal. so either we stick to the full name or the user name. vote for user name!

**Comment by manuelbernhardt** [comment]
Changed to "improvement". Yes the full name of someone appears on the profile page... why shouldn't it be there?

**Comment by manuelbernhardt** [comment]
If you mean the user list page, that is now fixed there

**Comment by stillinsky** [comment]
I mean that it is not consistant. the user list has http://frieseverhalen.delving.org:9001/users full names where the user name is not mentioned. Owner descriptions like in Object full views carry the user name (e.g. http://frieseverhalen.delving.org:9001/tw/object/4ec7fd410cf2ed12cdcdd6d9)

**Comment by manuelbernhardt** [comment]
Ok that should be fixed now
