### ISSUE TITLE
default pic for not uploaded objects and collections/stories

### ISSUE THREAD

**Issue by stillinsky** [delving/culture-hub#254]
When you create an object and do not upload a file the default view of the object is a big cross: http://frieseverhalen.delving.org:9001/stillinsky/object/4ec94f3f0cf2d36f8c0812d5
Can we change this to something more pleasant?

Also for the view in collections and stories whne now default picture was set.

**Comment by zemyatin** [comment]
nassauTheme branch will merge this fix in
