### ISSUE TITLE
Free text in page editor is messed up

### ISSUE THREAD

**Issue by stillinsky** [delving/culture-hub#266]
I tried to write a more complex free text passage (edit story page). The editor seems to be reversed: clicking enter makes the cursor jump to the beginning of the paragraph instrad of a new line. same with bullet points.

**Comment by manuelbernhardt** [comment]
Re-assigned to @zemyatin. Any idea what's going on with tinyMce?

**Comment by zemyatin** [comment]
Just noticed this as well, will investigate
