### ISSUE TITLE
upload object - no thumbnail is showing

### ISSUE THREAD

**Issue by stillinsky** [delving/culture-hub#267]
I have uplaoded an object but no thumbnail is showing: http://frieseverhalen.delving.org:9001/stillinsky/object/4ecc2e770cf2e75ac8a3359e
When editing this object I can still see it so it seems to be saved. The picture was very big, more than 4MB.

**Comment by manuelbernhardt** [comment]
I can see the image, and can generate all thumbnails:
- http://frieseverhalen.delving.org/thumbnail/4ecc2e770cf2e75ac8a3359e/500
- http://frieseverhalen.delving.org/thumbnail/4ecc2e770cf2e75ac8a3359e/350
- http://frieseverhalen.delving.org/thumbnail/4ecc2e770cf2e75ac8a3359e/180
- http://frieseverhalen.delving.org/thumbnail/4ecc2e770cf2e75ac8a3359e/100
- http://frieseverhalen.delving.org/thumbnail/4ecc2e770cf2e75ac8a3359e/80

Thus I'm closing this one.

**Comment by manuelbernhardt** [comment]
Confirmed when creating a new object
