### ISSUE TITLE
Solr-driven browsing in the CH

### ISSUE THREAD

**Issue by manuelbernhardt** [delving/culture-hub#272]
Also involves @manuelbernhardt

Currently we query mongo to fetch the items we browse:

```
def visibilityQuery(who: ObjectId) = MongoDBObject("$or" -> List(MongoDBObject("visibility.value" -> Visibility.PUBLIC.value), MongoDBObject("visibility.value" -> Visibility.PRIVATE.value, "user_id" -> who)))

def browseByUser(id: ObjectId, whoBrowses: ObjectId) = find(MongoDBObject("deleted" -> false, "user_id" -> id) ++ visibilityQuery(whoBrowses))
def browseAll(whoBrowses: ObjectId) = find(MongoDBObject("deleted" -> false) ++ visibilityQuery(whoBrowses))
```

This has its limits in that mongo can't go very much deeper: $or conditions only take simple fields and can't have $in conditions.

We'd need to be able to query solr to give back a list of Mongo IDs for the above queries:
- browse all: (for a given `PAGE`) IDs of all items of a `TYPE` (object, collection, story), only items that have visibility public
- browse by user: (for a given `PAGE`) IDs of all items of `TYPE` for a given `USER`

For the second query, the logic is as follows:

```
doc.visibility = 0 && (doc.userName = $userNameParam || $userNameParam in doc.collaborators) || doc.visibility = 10
```

**Comment by manuelbernhardt** [comment]
Started working on this today, starting to figure out SOLR syntax.

**Comment by kiivihal** [comment]
Make sure you use the hidden query filter mechanism. 

I think the basic code of this takes us less than an hour. So we could do it tomorrow morning.

**Comment by manuelbernhardt** [comment]
Ok, this now works more-or-less for objects. I don't think I need the HQFs because all the querying happens in the background - meaning, I am overriding the query via a `setSolrQuery`. Is that safe against smart users trying to hack the thing?

I could use a hand on getting the visibility query to work. There are no collaborators indexed yet because there are no collaborators but the basic skeletton for this should be really easy to set-up.
