### ISSUE TITLE
Decide on list of fields for culture-hub and their naming

### ISSUE THREAD

**Issue by manuelbernhardt** [delving/culture-hub#273]
@zemyatin @manuelbernhardt @geralddejong

**Comment by geralddejong** [comment]
Related to this, I presume: https://github.com/delving/sip-creator/issues/85

**Comment by manuelbernhardt** [comment]
DELVING GUYS (fields)

hubId:
- for UGC: owner/type/mongoId
- for MDR: orgId/spec/localRecordKey

delving_recordType (object | userCollection | story | dataset | ...)
title: "Some title"
description: 
owner: owner ("bob" / "FriesMuseum")
creator: creator ("bob" / "Van Gogh")

thumbnail: http://foo/barar/baz

mimeType (not filled in at the moment)
