### ISSUE TITLE
Introduce concept of 'my collection' 

### ISSUE THREAD

**Issue by stillinsky** [delving/culture-hub#286]
So far objects can be uploaded without being in a collection. When adding a story-page you can choose oebjects from 'no collection'. This should be renamed into the default 'my collection'. My collection should be also visible on collection page of user.

**Comment by manuelbernhardt** [comment]
Isn't the name 'my collection' a bit confusing, since the 'no
collection' is for objects that the user did not explicitly assign to
any collection? It's not like they added them to 'my collection'

Sent from my iPhone

On 26.11.2011, at 21:03, Juliane Stiller
reply@reply.github.com
wrote:

**Comment by stillinsky** [comment]
ok, i think every object which is not assigned to a certain collection should go into a default collection (which might only exist in the background). Maybe the name for it should be 'my objects'. I was just confused about the add pages section in 'edit story' which says 'select a collection' and then you can choose 'no collection'. Maybe a renaming would be enough here something like 'Other objects'.

**Comment by geralddejong** [comment]
I agree it should be called "Other Objects" rather than "No Collection".

**Comment by stillinsky** [comment]
find a new name for 'no collections'

**Comment by manuelbernhardt** [comment]
What about "Objects without a collection" ?

**Comment by stillinsky** [comment]
i think we could remove the a "objects without collection"

On Sat, Dec 17, 2011 at 4:59 AM, Manuel Bernhardt
reply@reply.github.com
wrote:

> What about "Objects without a collection" ?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/delving/culture-hub/issues/286#issuecomment-3189279

## 

Juliane Stiller
Delving B.V., San Francisco
mobile: (650) 479-5780
http://www.delving.eu

Contact me:  stillinsky

**Comment by manuelbernhardt** [comment]
What exactly do you mean with that? That the users cannot select
objects that are in no collection?

On Sat, Dec 17, 2011 at 4:31 PM, Juliane Stiller
reply@reply.github.com
wrote:

**Comment by stillinsky** [comment]
I mean that we can do that, just remove the 'a' to make it shorter.

On Sat, Dec 17, 2011 at 9:43 AM, Manuel Bernhardt
reply@reply.github.com
wrote:

> What exactly do you mean with that? That the users cannot select
> objects that are in no collection?
> 
> On Sat, Dec 17, 2011 at 4:31 PM, Juliane Stiller
> reply@reply.github.com
> wrote:
> 
> > i think we could remove the a "objects without collection"
> > 
> > On Sat, Dec 17, 2011 at 4:59 AM, Manuel Bernhardt
> > reply@reply.github.com
> > wrote:
> > 
> > > What about "Objects without a collection" ?
> > > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/delving/culture-hub/issues/286#issuecomment-3189279
> > 
> > ## 
> > 
> > Juliane Stiller
> > Delving B.V., San Francisco
> > mobile: (650) 479-5780
> > http://www.delving.eu
> > 
> > Contact me:  stillinsky
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/delving/culture-hub/issues/286#issuecomment-3189842
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/delving/culture-hub/issues/286#issuecomment-3190462

## 

Juliane Stiller
Delving B.V., San Francisco
mobile: (650) 479-5780
http://www.delving.eu

Contact me:  stillinsky
