### ISSUE TITLE
place-name labels can only be saved when known by geonames

### ISSUE THREAD

**Issue by stillinsky** [delving/culture-hub#298]
so far only Netherlands, I am not sure we want/can extend to global.

**Comment by manuelbernhardt** [comment]
Yes, this is a known thing. So far the dump provided by @glamcloud only has the netherlands in it. I think we should add the whole world, but it may make sense to think at how things should appear in the search then - maybe the country of the hub should be taken into account to show those results first.

Also I wonder what to do about language. Now the name that is saved is only in dutch I think. Do we need to be able to switch name when switching the language in the interface? That would mean saving all languages for each place link... may be a bit of an overkill. Or do we say that when the primary language of a hub is e.g. frisian the places are shown with frisian names, even for other countries? I think we should make this a design discussion / issue.

**Comment by glamcloud** [comment]
It just takes an hour or so to import the rest and make a new dump. You'll get it soon.

Different languages are handled by a quite big list of "alternate names". I'l add that too. 

/ tw 

## 

Thomas Wikman
Delving B.V., Skyttorp
http://www.delving.eu
mobile: +46 706 74 44 09  
skype: wikman_t

**Comment by manuelbernhardt** [comment]
Isn't the alternate names yet another list? At least that is how it is exposed in the web service. But maybe it is different in the source data

**Comment by manuelbernhardt** [comment]
I started working on a source format importer from geoname dumps, so that we can easily transfer geonames to our own storage format in mongo. That is, I think that for V 1.0 it will be OK to only have The Netherlands, so I'm removing this issue from the milestone.
