### ISSUE TITLE
Addin search results to collection with specifying collection - 404

### ISSUE THREAD

**Issue by stillinsky** [delving/culture-hub#299]
http://frieseverhalen.delving.org:9001/search?query=astrolabium
-add search results to add 'items to collections' 
-not choose a collection
-hit 'add to collection' -> 404

**Comment by stillinsky** [comment]
just realized the 404 happens without and with specifying the collection.

**Comment by manuelbernhardt** [comment]
Yes it's not implemented yet. Closing this one since it's not yet implemented.
