### ISSUE TITLE
Dataset page : info from solr

### ISSUE THREAD

**Issue by geralddejong** [delving/culture-hub#304]
Right now a dataset can easily appear enabled when it is not.

When on the page showing details of a dataset, it would be nice to have a link to search for all records in the index using delving_spec:{spec} so we can verify what's actually indexed.

http://frieseverhalen.delving.org/organizations/frieseverhalen/dataset/FriesFilmArchief

Perhaps even on the page listing all the datasets, there could be info retrieved through one big solr query and then shown.

**Comment by kiivihal** [comment]
This could be implemented as on big facet query every time the page it
reloaded. Or I can extend the explain API response to include this
information in both json or xml. So the choice should be if we add this in
knock-out or in the controller.

-Sjoerd

On Wed, Nov 30, 2011 at 10:17 AM, Gerald de Jong <
reply@reply.github.com

> wrote:
> 
> Right now a dataset can easily appear enabled when it is not.
> 
> When on the page showing details of a dataset, it would be nice to have a
> link to search for all records in the index using delving_spec:{spec} so we
> can verify what's actually indexed.
> 
> http://frieseverhalen.delving.org/organizations/frieseverhalen/dataset/FriesFilmArchief
> 
> Perhaps even on the page listing all the datasets, there could be info
> retrieved through one big solr query and then shown.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/delving/culture-hub/issues/304

## 

Sjoerd Siebinga
Delving B.V., Rotterdam
http://www.delving.eu
skype: sjoerdsiebinga
mobile: +31681926731

**Comment by geralddejong** [comment]
A link on the page so search results can be viewed would be good enough, and sometimes you want to see what the results look like so a link to a delving_spec search would be good to have anyway even if the numbers are added to the dataset list page.

In what sense is the facet query "big"?  I imagine it's not a large query, and that the result would be quick.

**Comment by kiivihal** [comment]
By big I meant just all records and it will be very fast.

On Wed, Nov 30, 2011 at 10:41 AM, Gerald de Jong <
reply@reply.github.com

> wrote:
> 
> A link on the page so search results can be viewed would be good enough,
> and sometimes you want to see what the results look like so a link to a
> delving_spec search would be good to have anyway even if the numbers are
> added to the dataset list page.
> 
> In what sense is the facet query "big"?  I imagine it's not a large query,
> and that the result would be quick.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/delving/culture-hub/issues/304#issuecomment-2957201

## 

Sjoerd Siebinga
Delving B.V., Rotterdam
http://www.delving.eu
skype: sjoerdsiebinga
mobile: +31681926731
