### ISSUE TITLE
Upload of new files not working

### ISSUE THREAD

**Issue by stillinsky** [delving/culture-hub#312]
it seems to work but then switches to a red-framed box. Saving does not save the uploaded file, but object is created

**Comment by manuelbernhardt** [comment]
This was in the logs:

```
11720626 [pool-5-thread-2] INFO org.apache.solr.client.solrj.impl.StreamingUpdateSolrServer - finished:    org.apache.solr.client.solrj.impl.StreamingUpdateSolrServer$Runner@3cbb2306
log4j:ERROR Failed to flush writer,
java.io.IOException: No space left on device
at java.io.FileOutputStream.writeBytes(Native Method)
at java.io.FileOutputStream.write(FileOutputStream.java:282)
at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:202)
at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:272)
```

I wonder why we did not get informed (the exception must be thrown in some place where we can hardly catch it). I will look into that, this is an infrastructure issue - there should be some monitoring / notification on the space on the server & some cleanup for the temporary uploaded files.

**Comment by stillinsky** [comment]
This reminds of another thing: Should we restrict the file size? Probably depends on the features we want to offer in future for  uploaded files.

**Comment by manuelbernhardt** [comment]
No idea about the file size. @kiivihal @geralddejong @zemyatin opinions?

**Comment by geralddejong** [comment]
Maybe there should be steps in file size.  Default case would allow for 100Mb or something, but if you check an "extra large" checkbox you can send 500Mb, so people do that consciously.
