### ISSUE TITLE
deleting objects in collection does not work

### ISSUE THREAD

**Issue by stillinsky** [delving/culture-hub#323]
trying to delete objects with 'delete button' and then save collection does not delete objects.

**Comment by manuelbernhardt** [comment]
Yes I noticed that too. Reassigned to @kiivihal - for some wicked reason, deletes sent to SOLR don't take effect immediately. I e.g. saw this for stories (not objects) locally, and have no idea what is happening.

**Comment by kiivihal** [comment]
They only take effect after a commit is called and a new search is
registered on the index. But I will look into it.

-Sjoerd

On Sat, Dec 3, 2011 at 8:12 PM, Manuel Bernhardt <
reply@reply.github.com

> wrote:
> 
> Yes I noticed that too. Reassigned to @kiivihal - for some wicked reason,
> deletes sent to SOLR don't take effect immediately. I e.g. saw this for
> stories (not objects) locally, and have no idea what is happening.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/delving/culture-hub/issues/323#issuecomment-3002358

## 

Sjoerd Siebinga
Delving B.V., Rotterdam
http://www.delving.eu
skype: sjoerdsiebinga
mobile: +31681926731

**Comment by manuelbernhardt** [comment]
Should work now
