### ISSUE TITLE
uploaded files do not show in thumbnails

### ISSUE THREAD

**Issue by stillinsky** [delving/culture-hub#334]
this worked fine for the last objects I uploaded but is not working anymore.

**Comment by stillinsky** [comment]
just realized that this might be related to this issue: https://github.com/delving/culture-hub/issues/312

**Comment by stillinsky** [comment]
It seems I can upload normally again. I seem to have messed around with the object before in way that it is not showing (object/4edeccb50cf2674c999134d4). It is visible in the browsing list but not in the object full-view

**Comment by manuelbernhardt** [comment]
Ok, closing this one then. I can't find the object btw.
