### ISSUE TITLE
super user with ability to remove UGC and block users

### ISSUE THREAD

**Issue by zemyatin** [delving/culture-hub#371]
This would be most useful to have in case of offensive content

**Comment by manuelbernhardt** [comment]
I think this one will eventually have to be split in more issues. I think we should aim at a very minimalistic, "get the job done" version of this, and then later investigate into adding support for community-driven moderation.

This would entail:
- add a `blocked` status to `DObject`, `UserCollection`, `Story` and `User`
- refactor all queries to use a handy builder object that builds `MongoDBObject`-s looking for `"deleted" -> false, "blocked" -> false`
- add a new `nodeAdmin` array to `User` and add a check in `DelvingController` (i.e. add it to the renderArgs)
- make new controller methods to block UGC objects, and users
- display a link to these actions, with a warning pop-up, on all "view" pages

**Comment by manuelbernhardt** [comment]
Also probably it should be logged who blocked an object, and at what time

**Comment by manuelbernhardt** [comment]
Ok, this ended up being implemented in the CH 1 iteration.
