### ISSUE TITLE
when adding items via dropbox - thumbnail radio buttons are gone

### ISSUE THREAD

**Issue by stillinsky** [delving/culture-hub#375]
when I add items to a collection via the dropbox on SERP then these items do not have a thumbnail radio-button

**Comment by manuelbernhardt** [comment]
What is SERP?

Indeed these don't have yet a radio-button because I haven't had time
to implement a way to use a heritage object's thumbnail URL as
collection or story thumbnail.

On Sat, Dec 17, 2011 at 4:58 PM, Juliane Stiller
reply@reply.github.com
wrote:

**Comment by stillinsky** [comment]
SERP = Search Result Page

On Sat, Dec 17, 2011 at 9:41 AM, Manuel Bernhardt
reply@reply.github.com
wrote:

> What is SERP?
> 
> Indeed these don't have yet a radio-button because I haven't had time
> to implement a way to use a heritage object's thumbnail URL as
> collection or story thumbnail.
> 
> On Sat, Dec 17, 2011 at 4:58 PM, Juliane Stiller
> reply@reply.github.com
> wrote:
> 
> > when I add items to a collection via the dropbox on SERP then these items do not have a thumbnail radio-button
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/delving/culture-hub/issues/375
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/delving/culture-hub/issues/375#issuecomment-3190458

## 

Juliane Stiller
Delving B.V., San Francisco
mobile: (650) 479-5780
http://www.delving.eu

Contact me:  stillinsky
