### ISSUE TITLE
europeana:object is THUMBNAIL

### ISSUE THREAD

**Issue by geralddejong** [delving/culture-hub#377]
The icn-record-definition.xml file has the THUMBNAIL set to isShownAt, whereas we typically have been mapping europeana:object to the thumbnail and isShownAt to the full-view.   I think it should be europeana:object that plays the role of THUMBNAIL.

**Comment by geralddejong** [comment]
Perhaps we should have a BACKUP_THUMBNAIL so that we can be clear that if one is absent the other can take its place.

**Comment by kiivihal** [comment]
We have such a mechanism when the urls go through our own cache. At the moment I don't think that is the case. You can add the default=path/to/thumbnail url on a per image basis. I will update the ICN mapping with some delving fields.
