### ISSUE TITLE
Large images with no scroll bar or discovery tool when enlarged

### ISSUE THREAD

**Issue by stillinsky** [delving/culture-hub#390]
Some images of objects become so big when licking 'enlarge' that they only show a small part of the image with no scroll bar or way of closing it, except the back button. 
Example: http://frieseverhalen.delving.org/frieseverhalen/object/TresoarGenealogie/11796
Tried it in Safari and Chrome, is for both the same.

**Comment by manuelbernhardt** [comment]
Reassigned to @zemyatin, I don't really know how to deal with these things :)
