### ISSUE TITLE
Hash mismatch

### ISSUE THREAD

**Issue by geralddejong** [delving/culture-hub#423]
The downloaded source contains a spurious space in "<delving-sip-source >" which is probably the reason that source has to be uploaded a second time.

**Comment by manuelbernhardt** [comment]
I think this is gone for good now

**Comment by geralddejong** [comment]
I just did a comparison between what source is uploaded and downloaded for Princessehof, and the result is two differently hashed files that have exactly the same size (un-gzipped 93449702 bytes) but different sizes (gzipped), and a diff of the two xml files reveals that the only difference is the order of the records.

**Comment by geralddejong** [comment]
One thing: the downloaded XML starts differently since the namespaces come out twice:

```
<delving-sip-source xmlns:dcterms="http://purl.org/dc/terms/" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:dc="http://purl.org/dc/elements/1.1/">
<input xmlns:dcterms="http://purl.org/dc/terms/" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:dc="http://purl.org/dc/elements/1.1/" id="60419a">
```

**Comment by geralddejong** [comment]
Each input also includes the namespaces:

```
<input xmlns:dcterms="http://purl.org/dc/terms/" xmlns:x link="http://www.w3.org/1999/xlink" xmlns:dc="http://purl.org/dc/elements/1.1/" id="83463">
```
