### ISSUE TITLE
Custom error pages

### ISSUE THREAD

**Issue by manuelbernhardt** [delving/culture-hub#43]
At the moment, error pages (500, 404 etc.) look quite bad (no theming, just a white page).

Those pages can be customized by adding `400.scala.html` etc. to `views/errors`

**Comment by kiivihal** [comment]
It is also important to add mailing functionality to this issue. So we get alerted when something out of the ordinary happens. Also the customization needs to be updated to use the groovy rendering instead of the scala.

**Comment by manuelbernhardt** [comment]
Mailing will be handled by #14

**Comment by manuelbernhardt** [comment]
In order to actually see the exception as in production, you need to take out the #{if mode == dev} part in the templates (or make it evaluate to false).

**Comment by manuelbernhardt** [comment]
Ok, I will close this one now. We have the custom pages and the e-mail and logging. I don't know yet if the e-mail work, we will find out when we have 505's on the server. At least the mock mailing works locally and it uses the same mechanism as sending the mails for registration, so I suppose it works.
