### ISSUE TITLE
Unresolved dependency building play2 branch

### ISSUE THREAD

**Issue by wsargent** [delving/culture-hub#433]
So if I check out the play2 branch:

/Users/wsargent/work/culture-hub/play2/culture-hub

and type "play update"

[20:53:11] wsargent:culture-hub git:(play2_) $ play update
[info] Loading project definition from /Users/wsargent/work/culture-hub/play2/culture-hub/project
[info] Set current project to culture-hub (in build file:/Users/wsargent/work/culture-hub/play2/culture-hub/)
[info] Updating {file:/Users/wsargent/work/culture-hub/play2/culture-hub/}framework-extensions...
[info] Resolving org.scala-lang#scala-library;2.9.1 ...
[info] Resolving play#play_2.9.1;2.0-RC1-SNAPSHOT ...
[info] Resolving play#templates_2.9.1;2.0-RC1-SNAPSHOT ...
[info] Resolving com.github.scala-incubator.io#scala-io-file_2.9.1;0.2.0 ...
[info] Resolving com.github.scala-incubator.io#scala-io-core_2.9.1;0.2.0 ...
[info] Resolving com.github.jsuereth.scala-arm#scala-arm_2.9.1;0.3 ...
[info] Resolving org.scala-lang#scala-compiler;2.9.1 ...
[info] Resolving play#anorm_2.9.1;2.0-RC1-SNAPSHOT ...
[info] Resolving org.scala-lang#scalap;2.9.1 ...
[info] Resolving org.jboss.netty#netty;3.2.6.Final ...
[info] Resolving org.slf4j#slf4j-api;1.6.2 ...
[info] Resolving org.slf4j#jul-to-slf4j;1.6.2 ...
[info] Resolving org.slf4j#jcl-over-slf4j;1.6.2 ...
[info] Resolving ch.qos.logback#logback-core;0.9.30 ...
[info] Resolving ch.qos.logback#logback-classic;0.9.30 ...
[info] Resolving se.scalablesolutions.akka#akka-actor;1.3-RC2 ...
[info] Resolving se.scalablesolutions.akka#akka-slf4j;1.3-RC2 ...
[info] Resolving com.typesafe.config#config_2.9.1;0.1.6 ...
[info] Resolving org.avaje#ebean;2.7.3 ...
[info] Resolving org.hibernate.javax.persistence#hibernate-jpa-2.0-api;1.0.1.Final ...
[info] Resolving com.h2database#h2;1.3.158 ...
[info] Resolving org.scala-tools#scala-stm_2.9.1;0.4 ...
[info] Resolving com.jolbox#bonecp;0.7.1.RELEASE ...
[info] Resolving com.google.guava#guava;r08 ...
[info] Resolving org.yaml#snakeyaml;1.9 ...
[info] Resolving org.hibernate#hibernate-validator;4.2.0.Final ...
[info] Resolving javax.validation#validation-api;1.0.0.GA ...
[info] Resolving org.springframework#spring-context;3.0.6.RELEASE ...
[info] Resolving org.springframework#spring-core;3.0.6.RELEASE ...
[info] Resolving org.springframework#spring-beans;3.0.6.RELEASE ...
[info] Resolving joda-time#joda-time;2.0 ...
[info] Resolving mysql#mysql-connector-java;5.1.17 ...
[info] Resolving javassist#javassist;3.12.1.GA ...
[info] Resolving commons-lang#commons-lang;2.6 ...
[info] Resolving com.ning#async-http-client;1.6.5 ...
[info] Resolving oauth.signpost#signpost-core;1.2.1.1 ...
[info] Resolving commons-codec#commons-codec;1.3 ...
[info] Resolving com.codahale#jerkson_2.9.1;0.5.0 ...
[info] Resolving org.codehaus.jackson#jackson-core-asl;[1.9.0,2.0.0) ...
[info] Resolving org.codehaus.jackson#jackson-mapper-asl;[1.9.0,2.0.0) ...
[info] Resolving org.reflections#reflections;0.9.5 ...
[info] Resolving dom4j#dom4j;1.6.1 ...
[info] Resolving xml-apis#xml-apis;1.0.b2 ...
[info] Resolving javax.servlet#javax.servlet-api;3.0.1 ...
[info] Resolving tyrex#tyrex;1.0.1 ...
[info] Resolving play#groovy-templates_2.9.1;0.1-SNAPSHOT ...
[warn]  module not found: play#groovy-templates_2.9.1;0.1-SNAPSHOT
[warn] ==== local: tried
[warn]   /Users/wsargent/play-2.0-RC1-SNAPSHOT/framework/../repository/local/play/groovy-templates_2.9.1/0.1-SNAPSHOT/ivys/ivy.xml
[warn] ==== jahia: tried
[warn]   http://maven.jahia.org/maven2/play/groovy-templates_2.9.1/0.1-SNAPSHOT/groovy-templates_2.9.1-0.1-SNAPSHOT.pom
[warn] ==== scala-tools: tried
[warn]   http://scala-tools.org/repo-releases/play/groovy-templates_2.9.1/0.1-SNAPSHOT/groovy-templates_2.9.1-0.1-SNAPSHOT.pom
[warn] ==== novus: tried
[warn]   http://repo.novus.com/snapshots/play/groovy-templates_2.9.1/0.1-SNAPSHOT/groovy-templates_2.9.1-0.1-SNAPSHOT.pom
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/play/groovy-templates_2.9.1/0.1-SNAPSHOT/groovy-templates_2.9.1-0.1-SNAPSHOT.pom
[warn] ==== Scala-Tools Maven2 Repository: tried
[warn]   http://scala-tools.org/repo-releases/play/groovy-templates_2.9.1/0.1-SNAPSHOT/groovy-templates_2.9.1-0.1-SNAPSHOT.pom
[info] Resolving com.jamonapi#jamon;2.7 ...
[info] Resolving oro#oro;2.0.8 ...
[info] Resolving javax.servlet#servlet-api;2.3 ...
[info] Resolving com.jamonapi#fdsapi;1.2 ...
[info] Resolving com.mongodb.casbah#casbah_2.9.1;2.1.5-1 ...
[info] Resolving com.mongodb.casbah#casbah-query_2.9.1;2.1.5-1 ...
[info] Resolving com.mongodb.casbah#casbah-commons_2.9.1;2.1.5-1 ...
[info] Resolving org.scala-tools.time#time_2.9.1;0.5 ...
[info] Resolving org.mongodb#mongo-java-driver;2.5.3 ...
[info] Resolving org.scalaj#scalaj-collection_2.9.1;1.2 ...
[info] Resolving com.mongodb.casbah#casbah-core_2.9.1;2.1.5-1 ...
[info] Resolving com.mongodb.casbah#casbah-gridfs_2.9.1;2.1.5-1 ...
[info] Resolving com.novus#salat-core_2.9.1;0.0.8-SNAPSHOT ...
[info] Resolving com.novus#salat-util_2.9.1;0.0.8-SNAPSHOT ...
[info] Resolving org.slf4j#slf4j-api;1.6.4 ...
[info] Resolving net.liftweb#lift-json_2.9.1;2.4-M4 ...
[info] Resolving com.thoughtworks.paranamer#paranamer;2.3 ...
[info] Resolving org.joda#joda-convert;1.2 ...
[info] Resolving org.codehaus.groovy#groovy;1.8.5 ...
[info] Resolving antlr#antlr;2.7.7 ...
[info] Resolving asm#asm;3.2 ...
[info] Resolving asm#asm-commons;3.2 ...
[info] Resolving asm#asm-tree;3.2 ...
[info] Resolving asm#asm-util;3.2 ...
[info] Resolving asm#asm-analysis;3.2 ...
[info] Resolving commons-collections#commons-collections;3.2.1 ...
[info] Resolving commons-httpclient#commons-httpclient;3.1 ...
[info] Resolving commons-logging#commons-logging;1.0.4 ...
[info] Resolving org.apache.commons#commons-email;1.2 ...
[info] Resolving javax.mail#mail;1.4.1 ...
[info] Resolving javax.activation#activation;1.1 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: play#groovy-templates_2.9.1;0.1-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[error] {file:/Users/wsargent/work/culture-hub/play2/culture-hub/}framework-extensions/_:update: sbt.ResolveException: unresolved dependency: play#groovy-templates_2.9.1;0.1-SNAPSHOT: not found
[error] Total time: 10 s, completed Feb 18, 2012 8:53:53 PM

How do I fix the unresolved dependency here?

**Comment by manuelbernhardt** [comment]
Hi Will,

yes indeed that part is still on my to-do list - I'll try to release this one next week. In order to get that dependency to work you need to:
- checkout https://github.com/manuelbernhardt/play-groovy-templates and do a `sbt publish-local`
- checkout https://github.com/manuelbernhardt/play2-groovy-templates and do a `sbt publish-local`

Note that the set-up assumes that you are using the usual /Users/foo/.ivy2 home directory, and not the custom one that Play 2 comes with. In order to do so you need to edit the `Play20/framework/build` script as well `Play20/play` and look for `-Dsbt.ivy.home`. When you've done that adjustment, run a `./build publish-local` in `Play20/framework` in order to re-build and publish Play in the normal ivy repo.

**Comment by wsargent** [comment]
Got a little further but having issues with play2-groovy-templates:

[18:39:12] wsargent:play2-groovy-templates git:(master*) $ sbt publish-local

#############################################################

 JRebel 4.5 (201109201828)
 (c) Copyright ZeroTurnaround OU, Estonia, Tartu.

 Over the last 30 days JRebel prevented 
 at least 0 redeploys/restarts saving you about 0 hours.

 Over the last 241 days JRebel prevented
 at least 511 redeploys/restarts saving you about 20.7 hours.

 This product is licensed to Personal
 until May 11, 2012
 for use with Scala classes only 
 for up to  developer seats on site. 

 The following plugins are disabled at the moment: 
- Click plugin (set -Drebel.click_plugin=true to enable)
  Reloads menu.xml menu definitions of Apache Click projects.
- Jersey plugin (set -Drebel.jersey_plugin=true to enable)
  Reloads Jersey configuration from Java annotations.
- Lift plugin (set -Drebel.lift_plugin=true to enable)
  Supports reloading singleton objects that extend RestHelper, MVCHelper,
  LiftScreen or Wizard.
- Oracle ADF Faces plugin (set -Drebel.adf_faces_plugin=true to enable)
  JRebel ADF Faces Plugin
- Seam-Wicket plugin (set -Drebel.seam_wicket_plugin=true to enable)
  Integration with load time weaving seam annotations to wicket classes
  (-javaagent:<path-to-jboss-seam-wicket-jar>)
- WebObjects plugin (set -Drebel.webobjects_plugin=true to enable)
  WebObjects JRebel Plugin

#############################################################

JRebel: A newer version '4.5.4' is available for download 
JRebel: from http://www.zeroturnaround.com/jrebel/upgrade/

[info] Loading project definition from /Users/wsargent/work/play2-groovy-templates/project
[info] Compiling 1 Scala source to /Users/wsargent/work/play2-groovy-templates/project/target/scala-2.9.1/sbt-0.11.2/classes...
[info] Set current project to groovy-templates (in build file:/Users/wsargent/work/play2-groovy-templates/)
[info] Updating {file:/Users/wsargent/work/play2-groovy-templates/}groovy-templates...
[info] Resolving org.scala-lang#scala-library;2.9.1 ...
[info] Resolving play#play_2.9.1;2.0-RC1-SNAPSHOT ...
[info] Resolving play#templates_2.9.1;2.0-RC1-SNAPSHOT ...
[info] Resolving com.github.scala-incubator.io#scala-io-file_2.9.1;0.2.0 ...
[info] Resolving com.github.scala-incubator.io#scala-io-core_2.9.1;0.2.0 ...
[info] Resolving com.github.jsuereth.scala-arm#scala-arm_2.9.1;0.3 ...
[info] Resolving org.scala-lang#scala-compiler;2.9.1 ...
[info] Resolving play#anorm_2.9.1;2.0-RC1-SNAPSHOT ...
[info] Resolving org.scala-lang#scalap;2.9.1 ...
[info] Resolving io.netty#netty;3.3.0.Final ...
[info] Resolving org.slf4j#slf4j-api;1.6.4 ...
[info] Resolving org.slf4j#jul-to-slf4j;1.6.4 ...
[info] Resolving org.slf4j#jcl-over-slf4j;1.6.4 ...
[info] Resolving ch.qos.logback#logback-core;1.0.0 ...
[info] Resolving ch.qos.logback#logback-classic;1.0.0 ...
[info] Resolving com.typesafe.akka#akka-actor;2.0-M2 ...
[info] Resolving com.typesafe.akka#akka-slf4j;2.0-M2 ...
[info] Resolving com.typesafe.config#config;0.2.1 ...
[info] Resolving org.avaje#ebean;2.7.3 ...
[info] Resolving org.hibernate.javax.persistence#hibernate-jpa-2.0-api;1.0.1.Final ...
[info] Resolving com.h2database#h2;1.3.158 ...
[info] Resolving org.scala-tools#scala-stm_2.9.1;0.4 ...
[info] Resolving com.jolbox#bonecp;0.7.1.RELEASE ...
[info] Resolving com.google.guava#guava;r08 ...
[info] Resolving org.yaml#snakeyaml;1.9 ...
[info] Resolving org.hibernate#hibernate-validator;4.2.0.Final ...
[info] Resolving javax.validation#validation-api;1.0.0.GA ...
[info] Resolving org.springframework#spring-context;3.0.7.RELEASE ...
[info] Resolving org.springframework#spring-core;3.0.7.RELEASE ...
[info] Resolving org.springframework#spring-beans;3.0.7.RELEASE ...
[info] Resolving joda-time#joda-time;2.0 ...
[info] Resolving org.joda#joda-convert;1.1 ...
[info] Resolving javassist#javassist;3.12.1.GA ...
[info] Resolving commons-lang#commons-lang;2.6 ...
[info] Resolving com.ning#async-http-client;1.7.0 ...
[info] Resolving org.jboss.netty#netty;3.2.7.Final ...
[info] Resolving oauth.signpost#signpost-core;1.2.1.1 ...
[info] Resolving commons-codec#commons-codec;1.3 ...
[info] Resolving com.codahale#jerkson_2.9.1;0.5.0 ...
[info] Resolving org.codehaus.jackson#jackson-core-asl;[1.9.0,2.0.0) ...
[info] Resolving org.codehaus.jackson#jackson-mapper-asl;[1.9.0,2.0.0) ...
[info] Resolving org.reflections#reflections;0.9.6 ...
[info] Resolving com.google.guava#guava;10.0 ...
[info] Resolving com.google.code.findbugs#jsr305;1.3.9 ...
[info] Resolving dom4j#dom4j;1.6.1 ...
[info] Resolving xml-apis#xml-apis;1.0.b2 ...
[info] Resolving javax.servlet#javax.servlet-api;3.0.1 ...
[info] Resolving javax.transaction#jta;1.1 ...
[info] Resolving tyrex#tyrex;1.0.1 ...
[info] Resolving net.sf.ehcache#ehcache-core;2.5.0 ...
[info] Resolving play#groovy-template-engine_2.9.1;0.1-SNAPSHOT ...
[warn]  module not found: play#groovy-template-engine_2.9.1;0.1-SNAPSHOT
[warn] ==== local: tried
[warn]   /Users/wsargent/.ivy2/local/play/groovy-template-engine_2.9.1/0.1-SNAPSHOT/ivys/ivy.xml
[warn] ==== jahia: tried
[warn]   http://maven.jahia.org/maven2/play/groovy-template-engine_2.9.1/0.1-SNAPSHOT/groovy-template-engine_2.9.1-0.1-SNAPSHOT.pom
[warn] ==== akka: tried
[warn]   http://akka.io/releases/play/groovy-template-engine_2.9.1/0.1-SNAPSHOT/groovy-template-engine_2.9.1-0.1-SNAPSHOT.pom
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/play/groovy-template-engine_2.9.1/0.1-SNAPSHOT/groovy-template-engine_2.9.1-0.1-SNAPSHOT.pom
[warn] ==== Scala-Tools Maven2 Repository: tried
[warn]   http://scala-tools.org/repo-releases/play/groovy-template-engine_2.9.1/0.1-SNAPSHOT/groovy-template-engine_2.9.1-0.1-SNAPSHOT.pom
[info] Resolving org.codehaus.groovy#groovy;1.8.5 ...
[info] Resolving antlr#antlr;2.7.7 ...
[info] Resolving asm#asm;3.2 ...
[info] Resolving asm#asm-commons;3.2 ...
[info] Resolving asm#asm-tree;3.2 ...
[info] Resolving asm#asm-util;3.2 ...
[info] Resolving asm#asm-analysis;3.2 ...
[info] Resolving com.jamonapi#jamon;2.7 ...
[info] Resolving oro#oro;2.0.8 ...
[info] Resolving javax.servlet#servlet-api;2.3 ...
[info] Resolving com.jamonapi#fdsapi;1.2 ...
[info] Resolving commons-collections#commons-collections;3.2.1 ...
[info] Resolving commons-io#commons-io;2.0 ...
[info] downloading http://akka.io/releases/com/typesafe/akka/akka-actor/2.0-M2/akka-actor-2.0-M2.jar ...
[info]  [SUCCESSFUL ] com.typesafe.akka#akka-actor;2.0-M2!akka-actor.jar (3368ms)
[info] downloading http://akka.io/releases/com/typesafe/akka/akka-slf4j/2.0-M2/akka-slf4j-2.0-M2.jar ...
[info]  [SUCCESSFUL ] com.typesafe.akka#akka-slf4j;2.0-M2!akka-slf4j.jar (356ms)
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: play#groovy-template-engine_2.9.1;0.1-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[error] {file:/Users/wsargent/work/play2-groovy-templates/}groovy-templates/*:update: sbt.ResolveException: unresolved dependency: play#groovy-template-engine_2.9.1;0.1-SNAPSHOT: not found
[error] Total time: 12 s, completed Feb 19, 2012 7:37:52 PM

**Comment by manuelbernhardt** [comment]
Hmm, this is odd. Did you publish the play-groovy-templates before the play2-groovy templates? (I may have to review the naming of these two... the play-groovy-templates is a generic engine extracted from play1, the play-groovy-templates is a plugin for Play 2 that uses it)

**Comment by wsargent** [comment]
Um... I don't remember what order I did it in.  It very easily could have been published in the wrong order.

**Comment by manuelbernhardt** [comment]
Hi Will,

the groovy template engine is now a maven dependency so this should deploy fine. Note that you'll need Play 2.0-SNAPSHOT for it to build, i.e. the last build from source. Hence I'll close this issue, feel free to ping me if you have more questions
