### ISSUE TITLE
Feedback on Unlock mechanism

### ISSUE THREAD

**Issue by stillinsky** [delving/culture-hub#482]
When unlocking a dataset the button's color is fading but the feedback is not very strong. It would be nice if the button would say 'Unlocked'. It seems that it locks itself after downloading the data into the Sip-Creator. Whether the set is locked or unlocked can only be determined by comparing the color to the other unlock buttons.
Furthermore, once you unlock, it is impossible to undo it until the data set is downloaded again (at least that is what it seems like)
By pressing the button the user should be able to undo the unlocking.

**Comment by manuelbernhardt** [comment]
The locking is not something meant to happen in the hub. It only
happens on download. In fact, the unlock button is a bit of a hack to
account for people forgetting to unlock a dataset in the sip-creator

Sent from my iPhone

On 03.05.2012, at 13:30, Juliane Stiller
reply@reply.github.com
wrote:
