### ISSUE TITLE
Themes configuration should be in the normal application config

### ISSUE THREAD

**Issue by manuelbernhardt** [delving/culture-hub#525]
Thinking about it, it makes no sense to keep the themes in a separate file. The data in there fits better the production.conf file for different deployments.

**Comment by kiivihal** [comment]
I think this is a good idea, as long as one production conf can serve multiple themes.

## 

Sjoerd Siebinga
Delving B.V., Rotterdam
http://www.delving.eu (http://www.delving.eu/)
skype: sjoerdsiebinga
mobile: +31681926731

**Comment by manuelbernhardt** [comment]
It would be like:

```
theme.default.name="default"
theme.default.domains="one, two, three"
```

Or actually we could use the HOCON notation (https://github.com/typesafehub/config/blob/master/HOCON.md)

**Comment by kiivihal** [comment]
Don't forget the facet and sort configuration that needs to be supported per domain. I think the HOCON notation is a very good way to move forward.

## 

Sjoerd Siebinga
Delving B.V., Rotterdam
http://www.delving.eu (http://www.delving.eu/)
skype: sjoerdsiebinga
mobile: +31681926731
