### ISSUE TITLE
Migrate old search specs to specs2, or use scala-test for all specs

### ISSUE THREAD

**Issue by manuelbernhardt** [delving/culture-hub#530]
Play2 by default comes with specs2. I'm not exactly fond of it so I wouldn't mind switching back to scala-test. For this we need to add this inside of the Main project settings:

```
testOptions in Test := Nil,
```

And migrate everything. Then also the not migrated search specs will work again

**Comment by manuelbernhardt** [comment]
Ok we actually can use both side-by-side

**Comment by kiivihal** [comment]
That is very nice. Does it run nicely on the CI server as well

**Comment by manuelbernhardt** [comment]
Yes of course, it's the exact same run system.

So now we can use scalatest again, which I find a lot nicer

Sent from my iPhone

On 24.08.2012, at 20:24, Sjoerd Siebinga notifications@github.com wrote:

That is very nice. Does it run nicely on the CI server as well

On Friday 24 August 2012 at 18:46, Manuel Bernhardt wrote:

> Ok we actually can use both side-by-side
> 
> —
> Reply to this email directly or view it on GitHub (
> https://github.com/delving/culture-hub/issues/530#issuecomment-8007987).

—
Reply to this email directly or view it on
GitHubhttps://github.com/delving/culture-hub/issues/530#issuecomment-8010617.
