### ISSUE TITLE
site list shows status "published" and "not published"

### ISSUE THREAD

**Issue by stillinsky** [delving/culture-hub#547]
should be only one of these

**Comment by manuelbernhardt** [comment]
I'm not sure what this means, or perhaps it has been fixed? When a page is published it says "Published", when not it says "Not published". So maybe this can be closed?

**Comment by stillinsky** [comment]
sorry was not clear about where it is. The status on the overview page of the tab 'website pages' shows the status 'published' and 'not published'. It can only one be one of these two.

**Comment by manuelbernhardt** [comment]
Fixed that, was a bug in the groovy templates engine removing the HTML comments, hence destroying some pages where knockoutJS was relying on them.
