### ISSUE TITLE
Fetch record-definitions at runtime

### ISSUE THREAD

**Issue by manuelbernhardt** [delving/culture-hub#580]
At the moment, record-definitions are built into a definitions.jar, then packaged together when the hub is built & deployed. So for each record-definition change the hub needs to be re-built and re-deployed.

Instead a better approach would be to have a kind of `SchemaFetcher` that would download the record definition and validation from the repository, for the starters perhaps only when the hub starts up (and later perhaps via an API call / UI button)

This would mean:
- implement a fetch class that downloads the enabled definitions and crosswalks (`RecordDefinition.enabledDefinitions`) from the definitions repository and stores them on disk
- in `Global`, call the downloading mechanism
- in `RecordDefinition`, replace getRecordDefinitionResources with something that lists the downloaded definitions from the filesystem

Some thoughts:
- we should start versioning record definitions / schemas. At least before starting source management this must be in place
- for versioned record definitions and such, there should be some sanity check via a hash to ensure that the same version wasn't changed

**Comment by glamcloud** [comment]
Great!!

And even better if we could see the current Field-markers (in reality a SOLR rec-def on top of icn, aff, tib etc) as a separate cross-walk-mapping and something being part of the source mapping. So fetch a given cross-walk using a another mapping as the source. Then all of it should be a bit more agnostic and future proof.
