### ISSUE TITLE
Create Dataset Record Definition list - ese shows twice

### ISSUE THREAD

**Issue by zemyatin** [delving/culture-hub#595]
On the create/edit dataset page, in the list of target record definitions, ese shows up twice

**Comment by manuelbernhardt** [comment]
Couldn't verify this one, I think it may have been related to a faulty application.conf, where those listings originate from.

**Comment by zemyatin** [comment]
http://playground.delving.org:9000/organizations/delving/dataset/add

I see "ese" twice in the target schema list on the right

e.

On Thu, Jul 12, 2012 at 9:03 AM, Manuel Bernhardt <
reply@reply.github.com

> wrote:
> 
> Couldn't verify this one, I think it may have been related to a faulty
> application.conf, where those listings originate from.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/delving/culture-hub/issues/595#issuecomment-6928384

## 

Delving B.V.
http://www.delving.eu
+31642112334
