### ISSUE TITLE
OAI-PMH problem repeating xmlns=""

### ISSUE THREAD

**Issue by geralddejong** [delving/culture-hub#596]
An error appears when attempting to harvest this dataset:

http://dimcon.delving.org/organizations/dimcon/api/oai-pmh?verb=ListRecords&metadataPrefix=ese&set=rkd-images

"error on line 1 at column 99: Attribute xmlns redefined"

This is visible in the browser's view-source mode.

The uploaded source starts with:

```
<?xml version='1.0' encoding='UTF-8'?>
<delving-sip-source xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.openarchives.org/OAI/2.0/">
<input xmlns="http://www.openarchives.org/OAI/2.0/" id="oai-AISdemo-1">
<header>
<identifier>oai:AISdemo:1</identifier>
<datestamp>2011-08-07T22:25:15Z</datestamp>
<setSpec>object:()</setSpec>
</header>
<metadata>
<record>
<priref>1</priref>
...
```

**Comment by geralddejong** [comment]
Perhaps the xmlns should not be appearing in the **input** tag.

**Comment by geralddejong** [comment]
I believe these are added somehow during creation for download, because the SIP-Creator strips the root namespace in its SourceConverter:

```
if (entry.getKey().isEmpty() || entry.getValue().trim().isEmpty()) continue;
```

**Comment by manuelbernhardt** [comment]
Hmm ok, I think they come from BaseX. Will have a look

**Comment by manuelbernhardt** [comment]
Forget about the previous comment. What you're saying is that the delving-sip-source should not contain the xmlns-only namespace?

The hub indeed makes use of them:

```
def buildNamespaces(attrs: Map[String, String]): String = {
  val attrBuilder = new StringBuilder
  attrs.foreach(ns => attrBuilder.append(if(ns._1.isEmpty) """xmlns="%s"""".format(ns._2) else """xmlns:%s="%s"""".format(ns._1, ns._2)).append(" "))
  attrBuilder.mkString.trim
}
```
