### ISSUE TITLE
sorting on dataset list page does not work

### ISSUE THREAD

**Issue by stillinsky** [delving/culture-hub#604]
The sorting on the dataset list page does not work. The little arrows indicate that it should work. So either these need to be removed or the sorting reintroduced.

**Comment by geralddejong** [comment]
Seems it is no longer working:

https://basecamp.com/1898565/projects/676100-rijksdienst-voor/messages/7133587-link-in-bron-detail

**Comment by zemyatin** [comment]
Most of the columns seem to sort properly ... except for the col with nr. of items ... i think that may be knockout related due to binding

**Comment by geralddejong** [comment]
It should probably default to sorting on the leftmost column.
