### ISSUE TITLE
workflow on dataset page is confusing

### ISSUE THREAD

**Issue by stillinsky** [delving/culture-hub#606]
The 'edit' button on the dataset list page brings you to the edit-page of the dataset but I guess when you are working with a dataset you should be able to quickly go to the actions. You only reach the action after saving the dataset or by clicking on the name of the dataset in the list. For now I don't know a solution to this, maybe another button in the list?

**Comment by manuelbernhardt** [comment]
Oops, referenced the wrong one in the commit.

Not sure what a good solution to that one is. Is the wrench icon not enough?

**Comment by zemyatin** [comment]
Do you mean you would like to see a link between the "edit" and the "action" page?

**Comment by stillinsky** [comment]
I am actually not sure I just found that confusing, maybe Sjoerd and Gerald should comment on that.

**Comment by manuelbernhardt** [comment]
@kiivihal @geralddejong Could you comment on this? If nobody is confused I'd like to close this issue.

**Comment by kiivihal** [comment]
I tend te agree. I would  be nice to be able to go from the Edit page to the Actions page. I found myself having to go via the dataset page a number of times too.

## 

Sjoerd Siebinga
Delving B.V., Rotterdam
http://www.delving.eu (http://www.delving.eu/)
skype: sjoerdsiebinga
mobile: +31681926731

**Comment by manuelbernhardt** [comment]
I'm not sure I understand. If you are on the edit page, press save, and you'll end up on the actions / view page.

If the edit link on the list page is too confusing, let's just remove it. There's one on the actions page anyway.

**Comment by stillinsky** [comment]
yes that might be a good solution and would avoid the misconception that the 'edit'-button lets you work with (meaning take actions on) the datasets.
In the list would only be one clickable link per which brings you to the detailed page and from there you can edit and take actions. I would prefer that.

**Comment by zemyatin** [comment]
Ok, here's what I did, and it seems to clear things up. In the dataset list name column, where we find the dataset name with a little wrench (meaning 'do stuff'), i've changed that to be styled like a button. This way it's immidiately clear that when you press that you can do stuff. The link to 'edit' the datset description is still a hyperlink in the last column, but it is less distracting now cause the buttons grab your attention.
