### ISSUE TITLE
Finished processing - "valid"

### ISSUE THREAD

**Issue by geralddejong** [delving/culture-hub#621]
When you first upload a dataset and it gets parsed, it only shows total records, since before processing there is nothing valid.  After processing, the progress bar completes but the "valid" count does not appear beside total records.  Only upon page refresh do you see it.  The valid number should be updated associated with processing, if not real-time at least at the beginning (set to zero?) and the end (page refresh no longer required)

**Comment by manuelbernhardt** [comment]
This is related to #602. No special event is fired server-side for
when valid counts are uploaded, hence no update happens on the
client-side

On Wed, Aug 1, 2012 at 4:13 PM, Gerald de Jong
reply@reply.github.com
wrote:
