### ISSUE TITLE
No datasets on org page

### ISSUE THREAD

**Issue by geralddejong** [delving/culture-hub#662]
http://dimcon.delving.org/organizations/dimcon

Shows no datasets, although the dataset list shows when you choose it.

**Comment by kiivihal** [comment]
Because of the issues with web sockets in Lighttpd you have to use port 9000 for the time being, then you can see all the datasets again.

## 

Sjoerd Siebinga
Delving B.V., Rotterdam
http://www.delving.eu (http://www.delving.eu/)
skype: sjoerdsiebinga
mobile: +31681926731
