### ISSUE TITLE
Notification email on force unlock 

### ISSUE THREAD

**Issue by kiivihal** [delving/culture-hub#698]
When someone force unlocks a data set it would be nice if the previous owner received a notification email. This is a nice partner measure with the sip-creator notification so that people don't accidentally work with orphaned data sets.

**Comment by geralddejong** [comment]
Yes, a very nice idea!   I could try and implement that.

**Comment by manuelbernhardt** [comment]
Feel free to go ahead! The best place to send the mail is in
`DataSetEventFeed#402`, and you'll have to implement a notification method
in `notifiers.Mails`.
