### ISSUE TITLE
Add a description field to the Virtual harvest Collection creation and display views

### ISSUE THREAD

**Issue by kiivihal** [delving/culture-hub#715]
Currently, there is no field in the virtual description where you can describe what the purpose and intention of this virtual collection.

So this issue should resolve the following usability issues
- Add description field to the creation page
- Add description field to the display view
- Turn search into textarea field
- Turn keywords into textarea field

And if possible:
- list with the linked datasets which of them have been mapped to the public format used by the virtual collection. 

Currently, you can only find this out by visiting each of the list sets. This is not very convenient if you want to see which sets will be included from the query into the linked results.

**Comment by manuelbernhardt** [comment]
Ok this should be done.

For the last point: all linked DataSets have the public format of the custom harvest collection in common. The format is the intersection of all formats of the linked sets. If there's no intersection, there is no public format (at least I remember this is how it works). As it isn't straightforward to display that information I skipped it for the time being.
