### ISSUE TITLE
knockout.js throws error in IE

### ISSUE THREAD

**Issue by zemyatin** [delving/culture-hub#72]
I tried loading the Culture-Hub in IE (running Parallels desktop) and pages using knockout threw errors and no data was loaded.
Fix for this might be found here?:
https://groups.google.com/group/knockoutjs/browse_thread/thread/368eb4559be1bde1?pli=1

**Comment by manuelbernhardt** [comment]
I remember I had this already in another application and it was
related to the jquery templating - what exactly are the errors in the
console? I will try to have a look at it when I have a free minute

Sent from my iPhone

On 08.10.2011, at 11:49, zemyatin
reply@reply.github.com
wrote:

**Comment by zemyatin** [comment]
User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; .NET4.0C; .NET4.0E)
Timestamp: Sat, 8 Oct 2011 10:26:52 UTC

Message: Object doesn't support this property or method
Line: 11
Char: 311
Code: 0
URI: http://192.168.1.9:9000/public/themes/common/javascripts/knockout.mapping-latest.js

**Comment by manuelbernhardt** [comment]
This should be fixed with the update of KO I did. Could you confirm?
