### ISSUE TITLE
Clean up the hacks in OAI-PMH

### ISSUE THREAD

**Issue by manuelbernhardt** [delving/culture-hub#734]
https://github.com/delving/culture-hub/commit/100b05a277738a3116998bf049d3527f84c86b00

There is a number of things wrong here:
- doing a text replace on the string to be rendered on the basis of the URL of MODS seems extremely wrong, the URL should be rendered in the first place at record generation time
- `URLEncoder.encode(record.asPmhId, "utf-8").replaceAll("%3A", ":")` looks like the replaceAll should be part of asPmhId.

I also have commented things inline.

**Comment by kiivihal** [comment]
Go read the pmh spec for identifiers first - there you see that the : is required and can't be escaped - before you make comments on things that were done intentionally. 

The URL is a issue at the sip-creator but I needed this now. Therefor a temporary solution was appropriate.

**Comment by manuelbernhardt** [comment]
I know the PMH spec. My point is that this piece of code is clear to you, because you wrote it, but not to anyone else who's going to read or maintain the code. Fixing the ":" escaping as well as URL-encoding the identifier looks like the job of `asPmhId`. Make your intent explicit:

```
def asPmhId(id: String) = {
  // as per PMH spec, the ":" in the identifier must not be escaped
  URLEncoder.encode(id, "utf-8").replaceAll("%3A", ":")
}
```

As for the MODS workaround, fine, but again, add a TODO and explain _why_ it is there.

Another issue is that by design, the MetadataCache and MetadataItem are meant to be agnostic to its usage so encapsulating `asPmhId` in it breaks this separation of concern, so that conversion method should be part of the OaiPmhService.

**Comment by manuelbernhardt** [comment]
And Sjoerd, stop identifying yourself with your code. I'm criticizing your code here, not you.
