### ISSUE TITLE
facet urls containing "&" breaking search

### ISSUE THREAD

**Issue by zemyatin** [delving/culture-hub#853]
If a facet's link value contains an ampersand the search chokes (both Hub and Api). I've put in a fix in the DIW to convert the ampersand to %26 but a better alternative would be for the HUB API and search mechanism to pick up this ampersand and deal with it there.

**Comment by manuelbernhardt** [comment]
The problem seems to be that despite a call to URLEncoder.encode in `SOLRQueryService#makeFacetQueryUrls` this ampersand is not encoded properly
