### ISSUE TITLE
Harden the indexing of geohashes

### ISSUE THREAD

**Issue by kiivihal** [delving/culture-hub#854]
Currently, when there is a problem in the UTM to lat,long conversion in the mapping that produces invalid lat,long pairs, it will discard the whole batch of 250 objects send to solr for indexing. This produces very strange and inconsistent behaviour with a higher number of valid records than actually indexed.

So I propose that we harden the code for checking valid lat,long pairs and discard when not valid during indexing. I will also implement similar checks on the mapping side, but the hub should just index everything without problems.

**Comment by manuelbernhardt** [comment]
This has been moved to Sip-Creator-land, where Gerald is making significant progress.

I suppose that until SOLR exhibits some kind of useable error handling, or we switch to ElasticSearch, we'll have to live with this rather unfortunate behavior. ElasticSearch only returns 200 OK when a document has indeed been indexed (including replication).
