### ISSUE TITLE
Make it possible under special conditions to retrieve up to 1000 records for the different KML flavours

### ISSUE THREAD

**Issue by kiivihal** [delving/culture-hub#855]
Currently, the maximum number of rows that can be returned in the search results is 500. For applications like 'erfgoed op de kaart' a 1000 would be a better number. Especially, since they cache these search results on the application side. Currently, retrieving 1000 rows from Solr in one go slows down, so it would be better to provide a chunked response where we feed the result of smaller queries to solr into a single API response.

We could also investigate the use of play 2 iteratees for this.

**Comment by manuelbernhardt** [comment]
Made the number of rows configurable. I don't think that trying to work-around SOLR being slow for large row numbers is the correct approach at this point anymore, rather, we should investigate these "dumps" in relation to the new rendering pipeline design.

**Comment by kiivihal** [comment]
But only make the configurable in relation to KML output formats.

On Wed, Mar 27, 2013 at 10:49 AM, Manuel Bernhardt <notifications@github.com

> wrote:
> 
> Made the number of rows configurable. I don't think that trying to
> work-around SOLR being slow for large row numbers is the correct approach
> at this point anymore, rather, we should investigate these "dumps" in
> relation to the new rendering pipeline design.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/delving/culture-hub/issues/855#issuecomment-15513843
> .

## 

Sjoerd Siebinga
Delving B.V., Rotterdam
http://www.delving.eu
skype: sjoerdsiebinga
mobile: +31681926731
