### ISSUE TITLE
Comma in Dataset Name

### ISSUE THREAD

**Issue by geralddejong** [delving/culture-hub#865]
I don't see any reason why a comma should be disallowed.

![Screen Shot 2013-04-03 at 3 05 46 PM](https://f.cloud.github.com/assets/184670/333701/5737ad8e-9c5f-11e2-865c-e5ab51abc23a.png)

**Comment by manuelbernhardt** [comment]
Because DataSet names are used in facets, and that special characters mess facet queries up, I went for a rather restrictive regular expression.
