### ISSUE TITLE
Named slice option to select all datasets

### ISSUE THREAD

**Issue by kiivihal** [delving/culture-hub#939]
Currently you have to select one or more datasets for the named slice to be valid. This creates or queries in the background. For organisations with a very large number of datasets, this will quickly exhaust the number of boolean operators in Solr. My proposal is that we have an option select all datasets and that then no additional filter is applied.

When all have been selected it should act in such a way that when new datasets are added these automatically come up in the named slice.

**Comment by zemyatin** [comment]
closed by commit 9ae54058eabc32ac00fad27861b1b97a2625311c
